set_property IOSTANDARD LVCMOS33 [get_ports {scan[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scan[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scan[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scan[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_code[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_code[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_code[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_code[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_code[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_code[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_code[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_code[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN R11 [get_ports enable]
set_property PACKAGE_PIN V1 [get_ports rst]
set_property PACKAGE_PIN G2 [get_ports {scan[3]}]
set_property PACKAGE_PIN C2 [get_ports {scan[2]}]
set_property PACKAGE_PIN C1 [get_ports {scan[1]}]
set_property PACKAGE_PIN H1 [get_ports {scan[0]}]
set_property PACKAGE_PIN A1 [get_ports {seg_code[4]}]
set_property PACKAGE_PIN A3 [get_ports {seg_code[2]}]
set_property PACKAGE_PIN A4 [get_ports {seg_code[1]}]
set_property PACKAGE_PIN B4 [get_ports {seg_code[0]}]


set_property PACKAGE_PIN B1 [get_ports {seg_code[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_code[5]}]
set_property PACKAGE_PIN B2 [get_ports {seg_code[6]}]
set_property PACKAGE_PIN D5 [get_ports {seg_code[7]}]


